### ISSUE TITLE
Move to .net standart

### ISSUE THREAD

**Issue by miker1423** [conekta/conekta-.net#12]
Just a quick question, why sticking with 4.5 and not moving to .NET Standard?

**Comment by daspuru** [comment]
I had to made some modifications to the code for working as .NET Standard and used it as a shared library between .NET Core and Xamarin.Forms. It is not so complicated and doable.

**Comment by eduardoconekta** [comment]
@daspuru can you share os some resources to this new .NET Standard ?

**Comment by daspuru** [comment]
I don't have the code @eduardoconekta , but I just created a new NetStandard library, imported all the code, made minor changes and compile. Almost all the code worked, and it was using 1.6, now with 2.0 maybe all your code can compile..

**Comment by eduardoconekta** [comment]
Ok thanks @daspuru  we will check 2.0 standard for further the next versions

**Comment by punicher94** [comment]
I want to use the library in an application in asp net core 2, but it gives me problems when sending the request, for example, when I want to create a customer, have you tried it with the asp net core 2 version?

**Comment by serge-wq** [comment]
Any updates on migrating more recent versions of .NET, including .NET 5?

**Comment by fcarrero** [comment]
we are working in a new version where will support new versions and features.

**Comment by fcarrero** [comment]
https://www.nuget.org/packages/Conekta.net/
