### ISSUE TITLE
Al crear un pedido, no permite procesarlo

### ISSUE THREAD

**Issue by chavezjal06** [conekta/conekta-.net#21]
Al crear un pedido, no permite procesarlo.

{
	"details": [
		{
			"debug_message": "The \"shipping_lines\" is missing.",
			"message": "El parametro \"shipping_lines\" es requerido.",
			"param": "shipping_lines",
			"code": "conekta.errors.parameter_validation.shipping_lines.missing"
		}
	],
	"object": "error",
	"type": "parameter_validation_error",
	"log_id": "5a1f0d50b795b078f2d0e73e"
}

shipping_lines ese campo es opcional

![image](https://user-images.githubusercontent.com/2577473/33395881-7c1b9d14-d50c-11e7-90d6-da17fa3d230a.png)

**Comment by mauroarcet** [comment]
@chavezjal06 Si al registrar tu compañía mencionaste que enviarías productos, shipping_lines será requerido.

Mándonos un email a soporte@conekta.com para realizar los cambios correspondoientes a tu compañía.
