### ISSUE TITLE
Public the official library in NuGet. 

### ISSUE THREAD

**Issue by Koronos** [conekta/conekta-.net#25]
There are some libraries in NuGet, but there isn't the official, why?

**Comment by eduardoconekta** [comment]
We are currently refactoring this library but sure we will publish an official version to Nuget soo @Koronos

**Comment by jmmartinezcdo** [comment]
Any update on this? The library has existed for years now, why it is still not on NuGet?

**Comment by holasoyeddy** [comment]
Do we have an update on this? I've only seen third-party libraries for Conekta on NuGet and would like to use this version instead.

**Comment by jmmartinezcdo** [comment]
> Do we have an update on this? I've only seen third-party libraries for Conekta on NuGet and would like to use this version instead.

I am currently working on this, in case it helps: https://github.com/Korvinet/Korvi.Conekta

**Comment by holasoyeddy** [comment]
> I am currently working on this, in case it helps: https://github.com/Korvinet/Korvi.Conekta

Thanks! I'll look into this in the meantime.
