### ISSUE TITLE
Buscar lista de ordenes por rango de fecha

### ISSUE THREAD

**Issue by marksandobal** [conekta/conekta-.net#33]
Hola que tal!
¿Existe alguna forma de obtener la lista de ordenes por rango de fecha en el método "where"?

var result = new  Order().@where(new JObject("{}"));

**Comment by eduenriquez** [comment]
si, @mauroarcet me podrias apoyar con esta consulta? recuerdo que `created_at.lte` y `created_at.gte` son los parametros pero no recuerdo como es el query

**Comment by marksandobal** [comment]
Hola @eduenriquez Gracias por responder. Esos campos son los que usamos en la consulta. Tambien ya resolvimos esta duda. Dejo el ejemplo por si alguien mas lo necesita. 

var result = new Order().@where(new JObject(@"{
                ""created_at.gte"": """ + fromDate+ @""",
                ""created_at.lte"": """ + toDate+ @""",
                ""last_payment_info.status"": ""paid"",
            }"));
