### ISSUE TITLE
SendFailure ó ProtocolError 

### ISSUE THREAD

**Issue by superedmundo** [conekta/conekta-.net#37]
Bajé la úlitma versión y al hacer la prueba de crear un customer con el ApiKey que vienen por default funciona bien, pero si pones uno tuyo, marca ProtocolError, comenté la línea: ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; en Requestor.cs, pero ahora manda SendFailure.

¿Cómo lo puedo arreglar?

**Comment by LuisAndres** [comment]
Sube el Framework a 4.5 o superior de tu proyecto y descomenta la linea que comentaste, a mi me soluciono el problema.

**Comment by leofischer** [comment]
@superedmundo - solucionaste tu problema?  Lo de Tls es requerido.  La librería no debería de comportar distinto cambiando el api_key, nos podrías pasar el error si lo tienes todavía?
