### ISSUE TITLE
antifraud_info is unknown field

### ISSUE THREAD

**Issue by cppmyjob** [conekta/conekta-.net#39]
createCustomer test contains unknown field - antifraud_info. API documentation https://developers.conekta.com/api#create-customer does not contain info about this field. Also I can't create customer without antifraud_info. If i delete the field then I get parameter_validation_error.

Why must I use antifraud_info? Where can i find info about the field?

**Comment by fcarrero** [comment]
https://developers.conekta.com/reference/createcustomer
now antifraud_info is a nullable object
