### ISSUE TITLE
Async/wait methods

### ISSUE THREAD

**Issue by genitalico** [conekta/conekta-.net#40]
Hi everyone, I dont see every codes of the lib yet but, the library do has methods non blocking?

I have methods for create costumers from api rest but this methods are non blocking, I decided to change the api rest raw for this lib,  but I see that for example: Customer customer = new conekta.Customer().create is bloking, then my fastest solution at the moment is it:
```
await Task.Run(
                () => {

                    customer = new conekta.Customer().create(json);

                });

```

is not elegant by I need using await by standardize, In the future you add this type method? 

if not maybe I can help you with it :p

**Comment by leofischer** [comment]
@genitalico - yeah, this should definitely be non blocking.  @Gustavilo will be taking over as maintainer on this project and will be looking at this in the coming weeks

**Comment by fcarrero** [comment]
this issue has been fixed in the new versions 6.x.x
