### ISSUE TITLE
Implement call to void order resource

### ISSUE THREAD

**Issue by glja021** [conekta/conekta-.net#43]
The .net library doesn't include a call to the void resource needed to cancel a pre-authorized order.

The java and nodejs versions added this endpoint as seen [here](https://github.com/conekta/conekta-node/issues/64) and [here](https://github.com/conekta/conekta-java/pull/78) I could submit the code if you are open to pull requests just let me know 👍

**Comment by fcarrero** [comment]
https://github.com/conekta/conekta-.net#catching-exception
we have implemented catching exception.
